services:
  client:
    build: ./client
    image: pdf-client-image
    container_name: pdf-client-container
    # env_file:
    #   - ./client/.env
    environment:
      - VITE_BASE_API_URL=http://localhost:4000/api
    ports:
      - "3000:8080"
    depends_on:
      - backend

  backend:
    build: ./api
    image: pdf-backend-image
    container_name: pdf-backend-container
    env_file:
      - ./api/.env
    ports:
      - "4000:5000"
