services:
  client:
    build: ./client
    image: pdf-client-image
    container_name: pdf-client-container
    environment:
      - VITE_BASE_API_URL=http://16.16.215.2:4000/api
    ports:
      - "3000:8080"
    restart: always
    depends_on:
      - backend

  backend:
    build: ./api
    # secrets:
    #   - backend_env_file
    image: pdf-backend-image
    container_name: pdf-backend-container
    env_file:
      - ./api/.env
    ports:
      - "4000:5000"
    restart: always
# secrets:
#   backend_env_file:
#     file: ./api/.env
