services:
  client:
    build: ./client
    image: pdf-client-image
    container_name: pdf-client-container
    env_file:
      - ./client/.env
    # environment:
    # - VITE_BASE_API_URL=http://16.16.215.2:4000/api/
    # - VITE_BASE_API_URL=http://localhost:4000/api
    ports:
      - "3000:8080"
    restart: always
    depends_on:
      - backend
      - Nginx

  Nginx:
    image: nginx:stable
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - nginx_networks
    command: ["nginx", "-g", "daemon off;"]

  backend:
    build: ./api
    # secrets:
    #   - backend_env_file
    image: pdf-backend-image
    container_name: pdf-backend-container
    env_file:
      - ./api/.env
    ports:
      - "4000:5000"
    restart: always
    networks:
      - nginx_networks
# secrets:
#   backend_env_file:
#     file: ./api/.env

networks:
  nginx_networks:
    driver: bridge
